spring.application.name=zomato
spring.datasource.url=jdbc:mysql://localhost:3306/zomato?createTableIfNotExists=true
spring.datasource.username=root
spring.datasource.password=Yatharth_1205
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
server.port=8080